package com.vparya12.common;

public class Constant {

	public static String GET_LOGIN_DATA = "SELECT * FROM USER WHERE USERNAME = :USERNAME AND PASSWORD = :PASSWORD ";
	
	public static String GET_ALL_DTH_NUMBER = "SELECT M.ID, DTHNUMBER, M.MOBILENUMBER,D.NETWORK,D.BALANCE,D.VALADITY, D.RECHARGEDATE, M.USERNAME,M.ALTNUMBER,D.AMOUNT,"
											+ " DATEDIFF(DATE_ADD(D.RECHARGEDATE,INTERVAL D.VALADITY DAY),CURRENT_DATE) AS LEFTDAYS, "
											+ " DATE_ADD(D.RECHARGEDATE,INTERVAL D.VALADITY DAY) AS NEXTRECHARGEDATE " 
											+ " FROM DTH D JOIN MOBILE M ON D.MOBILENUMBER=M.MOBILENUMBER WHERE D.ACTIVE=1 ORDER BY LEFTDAYS";
	
	public static String GET_ALL_MOBILE_NUMBER =  " SELECT *, DATEDIFF(DATE_ADD(RECHARGEDATE,INTERVAL VALADITY DAY),CURRENT_DATE) AS LEFTDAYS,"
												+ " DATE_ADD(RECHARGEDATE,INTERVAL VALADITY DAY) AS NEXTRECHARGEDATE FROM MOBILE WHERE ACTIVE=1 ORDER BY LEFTDAYS";
	
	public static String INSERT_NEW_MOBILE_FOR_DTH =  " INSERT INTO MOBILE (MOBILENUMBER, ALTNUMBER, NETWORK, USERNAME, RECHARGEDATE, AMOUNT, BALANCE, VALADITY, ACTIVE)"  
													+ " VALUES (:MOBILENUMBER, :ALTNUMBER, null, :USERNAME, now(), null, null, null, 1)"
													+ " ON DUPLICATE KEY UPDATE MOBILENUMBER = :MOBILENUMBER ";
	
	public static String INSERT_NEW_DTH = "INSERT INTO DTH (DTHNUMBER, MOBILENUMBER, RECHARGEDATE, NETWORK, BALANCE, VALADITY, AMOUNT) "
										+ " VALUES (:DTHNUMBER, :MOBILENUMBER, now(), :NETWORK, :BALANCE, :VALADITY, :AMOUNT) ";
	
	public static String INSERT_NEW_MOBILE =  " INSERT INTO MOBILE (MOBILENUMBER, ALTNUMBER, NETWORK, USERNAME, RECHARGEDATE, AMOUNT, BALANCE, VALADITY, ACTIVE)"  
											+ " VALUES (:MOBILENUMBER, :ALTNUMBER, :NETWORK, :USERNAME, now(), :AMOUNT, :BALANCE, :VALADITY, 1)"
											+ " ON DUPLICATE KEY UPDATE NETWORK = :NETWORK, RECHARGEDATE = CURRENT_DATE, AMOUNT = :AMOUNT,"
											+ " BALANCE = :BALANCE, VALADITY = :VALADITY, ACTIVE=1 ";

	public static String UPDATE_DTH = "UPDATE DTH SET  BALANCE = :BALANCE, VALADITY = :VALADITY, AMOUNT = :AMOUNT WHERE MOBILENUMBER = :MOBILENUMBER AND DTHNUMBER = :DTHNUMBER";
	
	public static String UPDATE_MOBILE = "UPDATE MOBILE SET RECHARGEDATE = now(), NETWORK= :NETWORK, BALANCE = :BALANCE, VALADITY = :VALADITY, AMOUNT = :AMOUNT WHERE ID = :ID";

	public static String RECHARGE_DTH = "UPDATE DTH SET PAYMENT = :PAYMENT, VALADITY = :VALADITY, AMOUNT = :AMOUNT, RECHARGEDATE = now() WHERE ID = :ID";
	
	public static String RECHARGE_MOBILE = "UPDATE MOBILE SET PAYMENT = :PAYMENT, VALADITY = :VALADITY, AMOUNT = :AMOUNT, RECHARGEDATE = now()  WHERE ID = :ID";

	public static String SIGNUP_USER = "INSERT INTO USERS (NAME,MOBILE_NUMBER,EMAIL_ID,PASSWORD,GENDER,ENABLED,ROLE_ID,CREATED_DATE) VALUES (:USERNAME, :MOBILENUMBER, :EMAIL, :PASSWORD, :GENDER, 0, 102, now())";

	public static String GET_MOBILE_BALANCE =" SELECT BALANCE FROM MOBILE WHERE ID = :ID";
	
	public static String GET_DTH_BALANCE ="SELECT SUM(DTH.BALANCE) AS BALANCE FROM DTH JOIN MOBILE ON DTH.MOBILENUMBER=MOBILE.MOBILENUMBER WHERE MOBILE.ID = :ID ";
}
