package com.anand_atm.common;

public class Constant {

	public static String GET_LOGIN_DATA = "SELECT * FROM USER WHERE USERNAME = :USERNAME AND PASSWORD = :PASSWORD ";
	
	public static String GET_ALL_DTH_NUMBER = "SELECT * FROM DTH";
	
	public static String GET_ALL_MOBILE_NUMBER = "SELECT * FROM MOBILE";
	
	public static String INSERT_NEW_DTH = "INSERT INTO DTH VALUES (:DTHNUMBER, :MOBILENUMBER, :ALTNUMBER, now(), :NETWORK, :PAYMENT, :USERNAME, :VALADITY, :AMOUNT, :TEST)";
	
	public static String INSERT_NEW_MOBILE = "INSERT INTO MOBILE VALUES (:MOBILENUMBER, :ALTNUMBER, :NETWORK, :USERNAME, now(), :AMOUNT, :PAYMENT, :VALADITY, :TEST, :TEST2)";
}
